# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/xenial64"

    config.vm.define "ubuntu" do |ubuntu|

        ubuntu.vm.provider "virtualbox" do |v|
            v.customize [ "modifyvm", :id ,"--memory", "1024" ]
            v.customize [ "modifyvm", :id, "--natdnshostresolver1", "on"]
            # v.gui = true
        end

        ubuntu.vm.hostname = "kube-master.project.com"
        ubuntu.vm.network "private_network", ip: "10.10.2.101"

        #ubuntu.vm.provision :puppet do |puppet|
            #puppet.hiera_config_path = "hiera/hiera.yaml"
            #puppet.manifests_path = "manifests"
            #puppet.manifest_file  = "site.pp"
            #puppet.module_path = "modules"
        #end

    end
end
